title: FedRAMP Tailored
description:
logo: /assets/fedramp-logo.png
repo: https://github.com/gsa/fedramp-tailored
google_analytics_ua: UA-48605964-46

# Site Status
banner: A website of the United States Government
phase: Production # alpha, beta, live

exclude:
- CONTRIBUTING.md
- Staticfile
- manifest.yml
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

sass:
  style: :compressed

scripts:
  - assets/js/uswds.min.js

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
